package com.realityengine.engine

import io.circe.Json
import com.realityengine.models.PagingDecision

/**
 * Output arbiter — RealityEngine_Machines docs/ARBITER_CONTRACT.md.
 *
 * A universal-vector position written by more than one contributor needs
 * something to decide the resolved value. Before this existed the merge blind-
 * wrote each machine's output in list order, so the last writer won. That order
 * is stable, which is worse than nondeterministic: a wrong resolution reproduces
 * perfectly and reads as correct.
 *
 * Every admissible rule is a commutative monoid (contract 4.1). That is the
 * load-bearing property: it is what lets the resolve phase be sharded across
 * cells in any order, and what lets four independent runtimes agree. `first` and
 * `last` — the two rules previously in use — satisfy none of it.
 */
object Arbiter {

  // ── Determinism (contract 3) ───────────────────────────────────────────────
  //
  // The ranking is not a status hierarchy. A deterministic contribution is
  // derivable from the corpus and IS(k) alone; a generated one is not derivable
  // from anything. If the irreproducible term wins a cell, IS(k+1) becomes
  // irreproducible and so does every determination downstream of it.
  val Deterministic = "deterministic"
  val Measured      = "measured"
  val Generated     = "generated"

  private val classOfProvider: Map[String, String] = Map(
    "machine" -> Deterministic,
    "sensor" -> Measured, "mqtt" -> Measured, "healthkit" -> Measured,
    "stream" -> Measured, "ui" -> Measured, "synthetic" -> Measured,
    "acp" -> Generated, "mcp" -> Generated, "localai" -> Generated
  )

  /** Unregistered surfaces are generated by default: misclassifying a generated
    * source as measured lets irreproducible content outrank a reading. */
  def determinismOf(provider: String): String = classOfProvider.getOrElse(provider, Generated)

  private val classRank = Map(Deterministic -> 3, Measured -> 2, Generated -> 1)

  // ── Severity (contract 4.3) ────────────────────────────────────────────────
  private val ragRank = Map("GREEN" -> 0, "AMBER" -> 1, "RED" -> 2)
  private val LifeSafetyRank = 3

  def severityRank(rag: Option[String], lifeSafety: Boolean): Int =
    if (lifeSafety) LifeSafetyRank else rag.flatMap(ragRank.get).getOrElse(0)

  /**
   * One contribution to one cell.
   *
   * `ragStatusCode` is what SEVERITY ranks by (4.3.1), so the gather phase must
   * carry the contribution rather than the bare value — discarding it before the
   * merge makes SEVERITY unimplementable.
   *
   * `cesId` is an OPAQUE KEY, not a sequence identifier (FOLD_PLACEMENT.md A3).
   * For a machine contribution it is the comma-joined, sorted, deduplicated set
   * of contributing sequences, so a folded value carries all of its evidence
   * rather than one arbitrarily chosen member. A one-element set renders as the
   * bare id, which is why single-contributor machines are unchanged. Nothing may
   * parse it back into a sequence — the two readers below treat it as a string
   * and stay correct:
   *
   *   - MEAN's canonical ordering sorts on it lexicographically;
   *   - the suppressed set is computed by structural equality of Contribution.
   */
  final case class Contribution(
    cell:           Int,
    value:          Double,
    provider:       String,
    originId:       String,
    cesId:          Option[String]    = None,
    outputVectorId: Option[String]    = None,
    ragStatusCode:  Option[String]    = None,
    lifeSafety:     Boolean           = false
  ) {
    def determinism: String = determinismOf(provider)
  }

  final case class ArbitrationRecord(
    instant:      Int,
    cell:         Int,
    rule:         String,
    resolved:     Double,
    contributors: List[Contribution],
    suppressed:   List[Contribution]
  )

  final case class RegistryEntry(
    cell:          Int,
    rule:          String,
    withinRank:    Option[String],
    providerRanks: Map[String, Int]
  )

  /**
   * Resolve one cell.
   *
   * Returns the value plus a record naming what was suppressed. A suppressed
   * agent assessment must stay attributable — "the agent's answer was discarded"
   * is precisely the operational fact the domain bus exists to surface.
   */
  def resolve(cell: Int, instant: Int,
              contributions: List[Contribution],
              entry: Option[RegistryEntry]): (Double, Option[ArbitrationRecord]) = {
    if (contributions.isEmpty) return (0.0, None)

    // A single contributor resolves to itself regardless of declared rule
    // (contract 4.5), and needs no record.
    if (contributions.size == 1) return (contributions.head.value, None)

    val rule = entry.map(_.rule).getOrElse("PRECEDENCE")
    val winners = rule match {
      case "OR" | "MAX" => maxBy(contributions)(_.value)
      case "AND" | "MIN" => minBy(contributions)(_.value)
      case "SEVERITY" =>
        val top = maxBy(contributions)(c => severityRank(c.ragStatusCode, c.lifeSafety).toDouble)
        maxBy(top)(_.value)
      case "MEAN" =>
        // Floating-point addition is not associative, so a parallel MEAN is not
        // order-independent. Canonical ordering makes it deterministic; the sum
        // is serial within a cell, and cells stay independent.
        val ordered = contributions.sortBy(c => (c.originId, c.cesId.getOrElse(""), c.outputVectorId.getOrElse("")))
        val mean = ordered.map(_.value).sum / ordered.size
        return (mean, Some(ArbitrationRecord(instant, cell, rule, mean, ordered, Nil)))
      case _ => // PRECEDENCE
        val ranks = entry.map(_.providerRanks).getOrElse(Map.empty)
        def rankOf(c: Contribution): Int =
          ranks.getOrElse(c.provider, classRank(c.determinism))
        val topRank = contributions.map(rankOf).max
        val atTop   = contributions.filter(rankOf(_) == topRank)
        entry.flatMap(_.withinRank) match {
          case Some("SEVERITY") =>
            val top = maxBy(atTop)(c => severityRank(c.ragStatusCode, c.lifeSafety).toDouble)
            maxBy(top)(_.value)
          case Some("MIN") | Some("AND") => minBy(atTop)(_.value)
          case Some("OR") | Some("MAX")  => maxBy(atTop)(_.value)
          case _                          => maxBy(atTop)(_.value) // 4.3a default
        }
    }
    val resolved   = winners.head.value
    val winnerSet  = winners.toSet
    val suppressed = contributions.filterNot(winnerSet.contains)
    (resolved, Some(ArbitrationRecord(instant, cell, rule, resolved, contributions, suppressed)))
  }

  private def maxBy(cs: List[Contribution])(f: Contribution => Double): List[Contribution] = {
    val best = cs.map(f).max
    cs.filter(c => f(c) == best)
  }

  private def minBy(cs: List[Contribution])(f: Contribution => Double): List[Contribution] = {
    val best = cs.map(f).min
    cs.filter(c => f(c) == best)
  }

  // ── Trigger-rule join (contract 4.3.1) ─────────────────────────────────────
  //
  // ragStatusCode is not carried on the output vector — 24 of 5128 have it. It
  // lives in metadata.triggerConfig.rules keyed by sequenceId and outputMatches,
  // on every machine. The join is total over the corpus (0 of 5128 unmatched);
  // where several rules match, max severity wins, which keeps the join a
  // commutative monoid and is the safe direction.
  def joinSeverity(metadata: Map[String, Json],
                   cesId: String, outputVector: Vector[Double]): Option[String] = {
    val rules = metadata.get("triggerConfig")
      .flatMap(_.hcursor.downField("rules").as[Vector[Json]].toOption)
      .getOrElse(Vector.empty)
    val hits = rules.filter { r =>
      val c = r.hcursor
      val seqOk = c.get[String]("sequenceId").toOption.contains(cesId)
      val outOk = c.downField("outputMatches").as[Vector[Double]].toOption.contains(outputVector)
      seqOk && outOk
    }.flatMap(_.hcursor.get[String]("ragStatusCode").toOption)
    if (hits.isEmpty) None else Some(hits.maxBy(r => ragRank.getOrElse(r, 0)))
  }

  /**
   * Governance for a FOLDED contribution — the join over its contributors'
   * severity ranks (FOLD_PLACEMENT.md §3).
   *
   * The fold gives the machine one value per cell but leaves it with no single
   * firing sequence, and severity ranking needs one `ragStatusCode`. 135 of 1328
   * corpus machines have an `outputMatches` pattern that maps to more than one
   * RAG code, so matching on the folded values alone is genuinely ambiguous for
   * them — the sequenceId filter is doing real work, which is why each
   * contributor is resolved against its OWN asserted values here and never
   * against the fold. A rule written for one CES's output need not match the
   * fold, and changing the matching semantics is not part of this move.
   *
   * The selection is the join over `severityRank`, which is already an ordered
   * chain — GREEN/absent 0 < AMBER 1 < RED 2 < lifeSafety 3 — so this is the
   * same lattice operation the fold vocabulary defines, applied to a chain the
   * codebase already had. It has the properties the fold contract demands, for
   * the same reasons: deterministic; symmetric, since max over a set does not
   * depend on enumeration order; closed, since it returns one contributor's rank
   * rather than inventing one; and safety-preserving, since a RED-governed
   * firing cannot be hidden by a GREEN one that folded alongside it. That last
   * property is what SEVERITY arbitration exists to guarantee — 2 cells under
   * `rule: SEVERITY` and 268 under `withinRank: SEVERITY` — so taking the join
   * preserves its intent rather than approximating it.
   *
   * Note the fold and the ranking can disagree by construction: `meet` can
   * select a value from a low-severity contributor while a high-severity one
   * also fired. That is intended — the value is the machine's composition, the
   * governance is how loudly a human is told about it, and they answer different
   * questions.
   *
   * Ties go to the lexicographically smallest `sequenceId`, and the winner's
   * decision is taken WHOLE. A decision composed from fields of different rules
   * describes no rule that exists; here the record is a single RAG code so
   * "whole" is trivially satisfied, but the selection is written as a choice of
   * contributor rather than a max over codes so it stays correct when this
   * runtime grows the rest of the PagingDecision.
   *
   * `contributors` are (sequenceId, that sequence's asserted values) in the
   * machine's canonical contributor order. None when no contributor resolved
   * governance, as today.
   */
  def joinGovernance(machine: com.realityengine.models.Machine,
                     contributors: Seq[(String, Vector[Double])]): Option[PagingDecision] = {
    val resolved = contributors.flatMap { case (seqId, values) =>
      com.realityengine.models.Governance.resolve(machine, seqId, values)
    }
    if (resolved.isEmpty) None
    // lifeSafety is never set by this runtime's machine contributions, so the
    // rank is the RAG chain alone. Passed explicitly rather than assumed, so the
    // day it is set this reads correctly without being revisited.
    else Some(resolved.minBy(d => (-severityRank(d.ragStatusCode, lifeSafety = false), d.sequenceId)))
  }
}
